#pragma once
#include <QString>
#include <QDate>
#include <QDateTime>
#include <vector>
#include <QSqlDatabase>
#include <QSqlQuery>
#include <QSqlError>
#include <QDebug>
#include <QStandardPaths>
#include <QDir>
#include <QList>
enum class RoomType { STANDARD, DELUXE, SUITE, PRESIDENTIAL };
inline QString roomTypeStr(RoomType t){ switch(t){ case RoomType::STANDARD: return "Standard"; case RoomType::DELUXE: return "Deluxe"; case RoomType::SUITE: return "Suite"; case RoomType::PRESIDENTIAL: return "Presidential"; } return ""; }
inline double roomPrice(RoomType t){ switch(t){ case RoomType::STANDARD: return 2500.0; case RoomType::DELUXE: return 5000.0; case RoomType::SUITE: return 10000.0; case RoomType::PRESIDENTIAL: return 25000.0; } return 0; }
struct Room { int number; RoomType type; bool isAvailable; int floor; QString amenities; Room():number(0),type(RoomType::STANDARD),isAvailable(true),floor(1){} Room(int n,RoomType t,int f,QString a=""):number(n),type(t),isAvailable(true),floor(f),amenities(a){} double pricePerNight()const{return roomPrice(type);} QString typeName()const{return roomTypeStr(type);} };
struct Guest { int id; QString name,phone,email,idProof,address; Guest():id(0){} Guest(int i,QString n,QString p,QString e,QString d,QString a=""):id(i),name(n),phone(p),email(e),idProof(d),address(a){} };
enum class BookingStatus { ACTIVE, CHECKED_OUT, CANCELLED };
inline QString bookingStatusStr(BookingStatus s){ switch(s){ case BookingStatus::ACTIVE: return "Active"; case BookingStatus::CHECKED_OUT: return "Checked Out"; case BookingStatus::CANCELLED: return "Cancelled"; } return ""; }
struct Booking { int bookingId,guestId,roomNumber; QDate checkIn,checkOut; BookingStatus status; double totalAmount,amountPaid; QString notes; Booking():bookingId(0),guestId(0),roomNumber(0),status(BookingStatus::ACTIVE),totalAmount(0),amountPaid(0){} int nights()const{return checkIn.daysTo(checkOut);} double balance()const{return totalAmount-amountPaid;} QString statusStr()const{return bookingStatusStr(status);} };
struct RestaurantItem { QString name,category; double price; };
inline QList<RestaurantItem> getMenu(){ return {{"Masala Chai","Beverages",60},{"Fresh Juice","Beverages",120},{"Coffee","Beverages",100},{"Mineral Water","Beverages",40},{"Aloo Paratha","Breakfast",180},{"Idli Sambar","Breakfast",160},{"English Breakfast","Breakfast",350},{"Poha","Breakfast",140},{"Dal Makhani","Lunch",280},{"Paneer Butter Masala","Lunch",320},{"Chicken Curry","Lunch",380},{"Biryani","Lunch",350},{"Tandoori Roti","Lunch",40},{"Grilled Fish","Dinner",450},{"Butter Naan","Dinner",50},{"Mutton Rogan Josh","Dinner",480},{"Veg Thali","Dinner",300},{"Samosa","Snacks",80},{"French Fries","Snacks",160},{"Club Sandwich","Snacks",220}}; }
struct RestaurantOrder { int orderId,bookingId,roomNumber,quantity; QString itemName,status; double amount; QDateTime orderTime; bool isPaid; RestaurantOrder():orderId(0),bookingId(0),roomNumber(0),quantity(1),amount(0),status("Pending"),isPaid(false){} };
struct LaundryItem { QString name; double price; };
inline QList<LaundryItem> getLaundryMenu(){ return {{"Shirt (Wash & Iron)",60},{"Trouser",80},{"Suit",200},{"Saree",150},{"Kurta",80},{"T-Shirt",50},{"Jeans",90},{"Bedsheet",120},{"Towel",40},{"Jacket",180}}; }
struct LaundryOrder { int orderId,bookingId,roomNumber,quantity; QString itemName; double amount; QDate orderDate,deliveryDate; bool isDelivered,isPaid; LaundryOrder():orderId(0),bookingId(0),roomNumber(0),quantity(1),amount(0),isDelivered(false),isPaid(false){} };
struct HotelData {
std::vector<Room> rooms; std::vector<Guest> guests; std::vector<Booking> bookings;
std::vector<RestaurantOrder> restaurantOrders; std::vector<LaundryOrder> laundryOrders;
int nextGuestId=1,nextBookingId=1,nextRestaurantId=1,nextLaundryId=1;
QSqlDatabase db;
void initDefaultRooms(){ rooms.clear(); for(int i=101;i<=110;i++) rooms.push_back(Room(i,RoomType::STANDARD,1,"AC, TV, WiFi")); for(int i=201;i<=208;i++) rooms.push_back(Room(i,RoomType::DELUXE,2,"AC, TV, WiFi, Mini-bar")); for(int i=301;i<=305;i++) rooms.push_back(Room(i,RoomType::SUITE,3,"AC, Smart TV, WiFi, Jacuzzi")); for(int i=401;i<=402;i++) rooms.push_back(Room(i,RoomType::PRESIDENTIAL,4,"Full Suite, Butler, Private Pool")); }
bool initDatabase(){ QString p=QStandardPaths::writableLocation(QStandardPaths::AppDataLocation); QDir().mkpath(p); p+="/hoteldata.db"; db=QSqlDatabase::addDatabase("QSQLITE"); db.setDatabaseName(p); if(!db.open()) return false; QSqlQuery q; q.exec("CREATE TABLE IF NOT EXISTS guests(id INTEGER PRIMARY KEY,name TEXT,phone TEXT,email TEXT,idproof TEXT,address TEXT)"); q.exec("CREATE TABLE IF NOT EXISTS bookings(id INTEGER PRIMARY KEY,guestId INTEGER,roomNumber INTEGER,checkIn TEXT,checkOut TEXT,status INTEGER,totalAmount REAL,amountPaid REAL,notes TEXT)"); q.exec("CREATE TABLE IF NOT EXISTS restaurant_orders(id INTEGER PRIMARY KEY,bookingId INTEGER,roomNumber INTEGER,itemName TEXT,quantity INTEGER,amount REAL,orderTime TEXT,isPaid INTEGER,status TEXT)"); q.exec("CREATE TABLE IF NOT EXISTS laundry_orders(id INTEGER PRIMARY KEY,bookingId INTEGER,roomNumber INTEGER,itemName TEXT,quantity INTEGER,amount REAL,orderDate TEXT,deliveryDate TEXT,isDelivered INTEGER,isPaid INTEGER)"); q.exec("CREATE TABLE IF NOT EXISTS room_status(roomNumber INTEGER PRIMARY KEY,isAvailable INTEGER)"); loadFromDatabase(); return true; }
void saveGuest(const Guest& g){ QSqlQuery q; q.prepare("INSERT OR REPLACE INTO guests VALUES(?,?,?,?,?,?)"); q.addBindValue(g.id);q.addBindValue(g.name);q.addBindValue(g.phone);q.addBindValue(g.email);q.addBindValue(g.idProof);q.addBindValue(g.address);q.exec(); }
void saveBooking(const Booking& b){ QSqlQuery q; q.prepare("INSERT OR REPLACE INTO bookings VALUES(?,?,?,?,?,?,?,?,?)"); q.addBindValue(b.bookingId);q.addBindValue(b.guestId);q.addBindValue(b.roomNumber);q.addBindValue(b.checkIn.toString("yyyy-MM-dd"));q.addBindValue(b.checkOut.toString("yyyy-MM-dd"));q.addBindValue((int)b.status);q.addBindValue(b.totalAmount);q.addBindValue(b.amountPaid);q.addBindValue(b.notes);q.exec(); }
void saveRestaurantOrder(const RestaurantOrder& o){ QSqlQuery q; q.prepare("INSERT OR REPLACE INTO restaurant_orders VALUES(?,?,?,?,?,?,?,?,?)"); q.addBindValue(o.orderId);q.addBindValue(o.bookingId);q.addBindValue(o.roomNumber);q.addBindValue(o.itemName);q.addBindValue(o.quantity);q.addBindValue(o.amount);q.addBindValue(o.orderTime.toString("yyyy-MM-dd hh:mm:ss"));q.addBindValue(o.isPaid?1:0);q.addBindValue(o.status);q.exec(); }
void saveLaundryOrder(const LaundryOrder& o){ QSqlQuery q; q.prepare("INSERT OR REPLACE INTO laundry_orders VALUES(?,?,?,?,?,?,?,?,?,?)"); q.addBindValue(o.orderId);q.addBindValue(o.bookingId);q.addBindValue(o.roomNumber);q.addBindValue(o.itemName);q.addBindValue(o.quantity);q.addBindValue(o.amount);q.addBindValue(o.orderDate.toString("yyyy-MM-dd"));q.addBindValue(o.deliveryDate.toString("yyyy-MM-dd"));q.addBindValue(o.isDelivered?1:0);q.addBindValue(o.isPaid?1:0);q.exec(); }
void saveRoomStatus(int n,bool a){ QSqlQuery q; q.prepare("INSERT OR REPLACE INTO room_status VALUES(?,?)"); q.addBindValue(n);q.addBindValue(a?1:0);q.exec(); }
void loadFromDatabase(){ guests.clear();bookings.clear();restaurantOrders.clear();laundryOrders.clear(); nextGuestId=1;nextBookingId=1;nextRestaurantId=1;nextLaundryId=1; QSqlQuery q; q.exec("SELECT * FROM guests"); while(q.next()){Guest g(q.value(0).toInt(),q.value(1).toString(),q.value(2).toString(),q.value(3).toString(),q.value(4).toString(),q.value(5).toString());guests.push_back(g);if(g.id>=nextGuestId)nextGuestId=g.id+1;} q.exec("SELECT * FROM bookings"); while(q.next()){Booking b;b.bookingId=q.value(0).toInt();b.guestId=q.value(1).toInt();b.roomNumber=q.value(2).toInt();b.checkIn=QDate::fromString(q.value(3).toString(),"yyyy-MM-dd");b.checkOut=QDate::fromString(q.value(4).toString(),"yyyy-MM-dd");b.status=(BookingStatus)q.value(5).toInt();b.totalAmount=q.value(6).toDouble();b.amountPaid=q.value(7).toDouble();b.notes=q.value(8).toString();bookings.push_back(b);if(b.bookingId>=nextBookingId)nextBookingId=b.bookingId+1;} q.exec("SELECT * FROM restaurant_orders"); while(q.next()){RestaurantOrder o;o.orderId=q.value(0).toInt();o.bookingId=q.value(1).toInt();o.roomNumber=q.value(2).toInt();o.itemName=q.value(3).toString();o.quantity=q.value(4).toInt();o.amount=q.value(5).toDouble();o.orderTime=QDateTime::fromString(q.value(6).toString(),"yyyy-MM-dd hh:mm:ss");o.isPaid=q.value(7).toInt()==1;o.status=q.value(8).toString();restaurantOrders.push_back(o);if(o.orderId>=nextRestaurantId)nextRestaurantId=o.orderId+1;} q.exec("SELECT * FROM laundry_orders"); while(q.next()){LaundryOrder o;o.orderId=q.value(0).toInt();o.bookingId=q.value(1).toInt();o.roomNumber=q.value(2).toInt();o.itemName=q.value(3).toString();o.quantity=q.value(4).toInt();o.amount=q.value(5).toDouble();o.orderDate=QDate::fromString(q.value(6).toString(),"yyyy-MM-dd");o.deliveryDate=QDate::fromString(q.value(7).toString(),"yyyy-MM-dd");o.isDelivered=q.value(8).toInt()==1;o.isPaid=q.value(9).toInt()==1;laundryOrders.push_back(o);if(o.orderId>=nextLaundryId)nextLaundryId=o.orderId+1;} q.exec("SELECT * FROM room_status"); while(q.next()){int rn=q.value(0).toInt();bool av=q.value(1).toInt()==1;for(auto& r:rooms)if(r.number==rn){r.isAvailable=av;break;}} }
Room* findRoom(int n){for(auto& r:rooms)if(r.number==n)return &r;return nullptr;}
Guest* findGuest(int i){for(auto& g:guests)if(g.id==i)return &g;return nullptr;}
Booking* findBooking(int i){for(auto& b:bookings)if(b.bookingId==i)return &b;return nullptr;}
int availableCount()const{int c=0;for(auto& r:rooms)if(r.isAvailable)c++;return c;}
int occupiedCount()const{return(int)rooms.size()-availableCount();}
double totalRevenue()const{double t=0;for(auto& b:bookings)if(b.status!=BookingStatus::CANCELLED)t+=b.amountPaid;for(auto& o:restaurantOrders)if(o.isPaid)t+=o.amount;for(auto& o:laundryOrders)if(o.isPaid)t+=o.amount;return t;}
double pendingRestaurantBill(int r)const{double t=0;for(auto& o:restaurantOrders)if(o.roomNumber==r&&!o.isPaid)t+=o.amount;return t;}
double pendingLaundryBill(int r)const{double t=0;for(auto& o:laundryOrders)if(o.roomNumber==r&&!o.isPaid)t+=o.amount;return t;}
};
